@startuml EUC4InformalSequenceDiagramIteration2

skinparam linetype ortho
'skinparam backgroundColor transparent
'skinparam handwritten true
'skinparam monochrome true
'left to right direction
skinparam sequenceMessageAlign direction
hide empty members
hide empty description
skinparam classAttributeIconSize 0
skinparam style strictuml

actor User
participant ":ClientGui" as ClientGui
participant ":Register Events Controller" as RegisterEventsController
participant ":DBManager" as DBManager

User --> ClientGui : <<Clicks "Register Event" button>>
ClientGui -> RegisterEventsController : retrieves list of events
RegisterEventsController -> DBManager : get list of events from DB
DBManager --> RegisterEventsController : list of events
RegisterEventsController --> ClientGui : list of events
ClientGui --> User : displays list of events

@enduml