@startuml EUC3InformalSequenceDiagramIteration2


skinparam linetype ortho
'skinparam backgroundColor transparent
'skinparam handwritten true
'skinparam monochrome true
'left to right direction
skinparam sequenceMessageAlign direction
hide empty members
hide empty description
skinparam classAttributeIconSize 0
skinparam style strictuml

actor "System User" as User
participant ":EventProposalUI" as EventProposalUI
participant ":EventProposalController" as EventProposalController
participant ":DBManager" as DBManager

User --> EventProposalUI : <<Select "Submit Proposal" button>>
EventProposalUI --> User : Display Event Form
User --> EventProposalUI : <<Fill in Event Form>>
EventProposalUI -> EventProposalController : sends details
EventProposalController -> DBManager : saves details
DBManager --> EventProposalController : returns success
EventProposalController --> EventProposalUI : returns confirmation message
EventProposalUI --> User : Display "Pending Review and Payment Invoice"

@enduml